SELECT ?lang ?article WHERE {
  VALUES ?lang { "af" "en" "nr" "nso" "st" "ss" "ts" "tn" "ve" "xh" "zu" }

  ?article schema:about wd:Q43033 ;
           schema:isPartOf ?wiki .

  FILTER(CONTAINS(STR(?wiki), CONCAT(?lang, ".wikipedia.org")))
}
